### ISSUE TITLE
Microsoft Edge 130.0.2849.68 decrypt failed

### ISSUE THREAD

**Issue by hueta** [xaitax/Chrome-App-Bound-Encryption-Decryption#4]
when code ran against latest edge, on Decrypt stage it fails with error
code: HRESULT(0x80070057), message: "The parameter is incorrect." 

I have checked clsid and iid for lates version, they seems correct

**Comment by iosmisrsq** [comment]
> when code ran against latest edge, on Decrypt stage it fails with error code: HRESULT(0x80070057), message: "The parameter is incorrect."
> 
> I have checked clsid and iid for lates version, they seems correct

Same problem, I'm guessing it's because the Edge's rpc parameter and server-side implement is different  from chrome
